// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineClient interface {
	Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error)
	SubscribeToOrderUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Engine_SubscribeToOrderUpdatesClient, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/tcb.matching_engine.Engine/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/tcb.matching_engine.Engine/ProcessMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/tcb.matching_engine.Engine/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error) {
	out := new(BookOutput)
	err := c.cc.Invoke(ctx, "/tcb.matching_engine.Engine/FetchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) SubscribeToOrderUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Engine_SubscribeToOrderUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Engine_ServiceDesc.Streams[0], "/tcb.matching_engine.Engine/SubscribeToOrderUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &engineSubscribeToOrderUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Engine_SubscribeToOrderUpdatesClient interface {
	Recv() (*OrderUpdateEvent, error)
	grpc.ClientStream
}

type engineSubscribeToOrderUpdatesClient struct {
	grpc.ClientStream
}

func (x *engineSubscribeToOrderUpdatesClient) Recv() (*OrderUpdateEvent, error) {
	m := new(OrderUpdateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EngineServer is the server API for Engine service.
// All implementations must embed UnimplementedEngineServer
// for forward compatibility
type EngineServer interface {
	Process(context.Context, *Order) (*OutputOrders, error)
	ProcessMarket(context.Context, *Order) (*OutputOrders, error)
	Cancel(context.Context, *Order) (*Order, error)
	FetchBook(context.Context, *BookInput) (*BookOutput, error)
	SubscribeToOrderUpdates(*SubscribeRequest, Engine_SubscribeToOrderUpdatesServer) error
	mustEmbedUnimplementedEngineServer()
}

// UnimplementedEngineServer must be embedded to have forward compatible implementations.
type UnimplementedEngineServer struct {
}

func (UnimplementedEngineServer) Process(context.Context, *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedEngineServer) ProcessMarket(context.Context, *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarket not implemented")
}
func (UnimplementedEngineServer) Cancel(context.Context, *Order) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedEngineServer) FetchBook(context.Context, *BookInput) (*BookOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBook not implemented")
}
func (UnimplementedEngineServer) SubscribeToOrderUpdates(*SubscribeRequest, Engine_SubscribeToOrderUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToOrderUpdates not implemented")
}
func (UnimplementedEngineServer) mustEmbedUnimplementedEngineServer() {}

// UnsafeEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServer will
// result in compilation errors.
type UnsafeEngineServer interface {
	mustEmbedUnimplementedEngineServer()
}

func RegisterEngineServer(s grpc.ServiceRegistrar, srv EngineServer) {
	s.RegisterService(&Engine_ServiceDesc, srv)
}

func _Engine_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcb.matching_engine.Engine/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Process(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_ProcessMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).ProcessMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcb.matching_engine.Engine/ProcessMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).ProcessMarket(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcb.matching_engine.Engine/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Cancel(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_FetchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).FetchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcb.matching_engine.Engine/FetchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).FetchBook(ctx, req.(*BookInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_SubscribeToOrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServer).SubscribeToOrderUpdates(m, &engineSubscribeToOrderUpdatesServer{stream})
}

type Engine_SubscribeToOrderUpdatesServer interface {
	Send(*OrderUpdateEvent) error
	grpc.ServerStream
}

type engineSubscribeToOrderUpdatesServer struct {
	grpc.ServerStream
}

func (x *engineSubscribeToOrderUpdatesServer) Send(m *OrderUpdateEvent) error {
	return x.ServerStream.SendMsg(m)
}

// Engine_ServiceDesc is the grpc.ServiceDesc for Engine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcb.matching_engine.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Engine_Process_Handler,
		},
		{
			MethodName: "ProcessMarket",
			Handler:    _Engine_ProcessMarket_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Engine_Cancel_Handler,
		},
		{
			MethodName: "FetchBook",
			Handler:    _Engine_FetchBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToOrderUpdates",
			Handler:       _Engine_SubscribeToOrderUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/matching-engine.proto",
}
