// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/matching-engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_buy  Side = 0
	Side_sell Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "buy",
		1: "sell",
	}
	Side_value = map[string]int32{
		"buy":  0,
		"sell": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_matching_engine_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_pkg_proto_matching_engine_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Side                   `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=tcb.matching_engine.Side" json:"Type,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	Pair          string                 `protobuf:"bytes,5,opt,name=Pair,json=pair,proto3" json:"Pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetType() Side {
	if x != nil {
		return x.Type
	}
	return Side_buy
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type OutputOrders struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrdersProcessed string                 `protobuf:"bytes,1,opt,name=OrdersProcessed,json=orders_processed,proto3" json:"OrdersProcessed,omitempty"`
	PartialOrder    string                 `protobuf:"bytes,2,opt,name=PartialOrder,json=partial_order,proto3" json:"PartialOrder,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutputOrders) Reset() {
	*x = OutputOrders{}
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputOrders) ProtoMessage() {}

func (x *OutputOrders) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputOrders.ProtoReflect.Descriptor instead.
func (*OutputOrders) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{1}
}

func (x *OutputOrders) GetOrdersProcessed() string {
	if x != nil {
		return x.OrdersProcessed
	}
	return ""
}

func (x *OutputOrders) GetPartialOrder() string {
	if x != nil {
		return x.PartialOrder
	}
	return ""
}

type BookInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookInput) Reset() {
	*x = BookInput{}
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInput) ProtoMessage() {}

func (x *BookInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInput.ProtoReflect.Descriptor instead.
func (*BookInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{2}
}

func (x *BookInput) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *BookInput) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BookArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceAmount   []string               `protobuf:"bytes,1,rep,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookArray) Reset() {
	*x = BookArray{}
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookArray) ProtoMessage() {}

func (x *BookArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookArray.ProtoReflect.Descriptor instead.
func (*BookArray) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{3}
}

func (x *BookArray) GetPriceAmount() []string {
	if x != nil {
		return x.PriceAmount
	}
	return nil
}

type BookOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buys          []*BookArray           `protobuf:"bytes,1,rep,name=Buys,proto3" json:"Buys,omitempty"`
	Sells         []*BookArray           `protobuf:"bytes,2,rep,name=Sells,proto3" json:"Sells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookOutput) Reset() {
	*x = BookOutput{}
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookOutput) ProtoMessage() {}

func (x *BookOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookOutput.ProtoReflect.Descriptor instead.
func (*BookOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{4}
}

func (x *BookOutput) GetBuys() []*BookArray {
	if x != nil {
		return x.Buys
	}
	return nil
}

func (x *BookOutput) GetSells() []*BookArray {
	if x != nil {
		return x.Sells
	}
	return nil
}

var File_pkg_proto_matching_engine_proto protoreflect.FileDescriptor

const file_pkg_proto_matching_engine_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/matching-engine.proto\x12\x13tcb.matching_engine\"\x88\x01\n" +
	"\x05Order\x12-\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x19.tcb.matching_engine.SideR\x04type\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\tR\x05price\x12\x12\n" +
	"\x04Pair\x18\x05 \x01(\tR\x04pair\"^\n" +
	"\fOutputOrders\x12)\n" +
	"\x0fOrdersProcessed\x18\x01 \x01(\tR\x10orders_processed\x12#\n" +
	"\fPartialOrder\x18\x02 \x01(\tR\rpartial_order\"5\n" +
	"\tBookInput\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\".\n" +
	"\tBookArray\x12!\n" +
	"\fprice_amount\x18\x01 \x03(\tR\vpriceAmount\"v\n" +
	"\n" +
	"BookOutput\x122\n" +
	"\x04Buys\x18\x01 \x03(\v2\x1e.tcb.matching_engine.BookArrayR\x04Buys\x124\n" +
	"\x05Sells\x18\x02 \x03(\v2\x1e.tcb.matching_engine.BookArrayR\x05Sells*\x19\n" +
	"\x04Side\x12\a\n" +
	"\x03buy\x10\x00\x12\b\n" +
	"\x04sell\x10\x012\xb2\x02\n" +
	"\x06Engine\x12H\n" +
	"\aProcess\x12\x1a.tcb.matching_engine.Order\x1a!.tcb.matching_engine.OutputOrders\x12N\n" +
	"\rProcessMarket\x12\x1a.tcb.matching_engine.Order\x1a!.tcb.matching_engine.OutputOrders\x12@\n" +
	"\x06Cancel\x12\x1a.tcb.matching_engine.Order\x1a\x1a.tcb.matching_engine.Order\x12L\n" +
	"\tFetchBook\x12\x1e.tcb.matching_engine.BookInput\x1a\x1f.tcb.matching_engine.BookOutputB\vZ\tpkg/protob\x06proto3"

var (
	file_pkg_proto_matching_engine_proto_rawDescOnce sync.Once
	file_pkg_proto_matching_engine_proto_rawDescData []byte
)

func file_pkg_proto_matching_engine_proto_rawDescGZIP() []byte {
	file_pkg_proto_matching_engine_proto_rawDescOnce.Do(func() {
		file_pkg_proto_matching_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_matching_engine_proto_rawDesc), len(file_pkg_proto_matching_engine_proto_rawDesc)))
	})
	return file_pkg_proto_matching_engine_proto_rawDescData
}

var file_pkg_proto_matching_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_matching_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_matching_engine_proto_goTypes = []any{
	(Side)(0),            // 0: tcb.matching_engine.Side
	(*Order)(nil),        // 1: tcb.matching_engine.Order
	(*OutputOrders)(nil), // 2: tcb.matching_engine.OutputOrders
	(*BookInput)(nil),    // 3: tcb.matching_engine.BookInput
	(*BookArray)(nil),    // 4: tcb.matching_engine.BookArray
	(*BookOutput)(nil),   // 5: tcb.matching_engine.BookOutput
}
var file_pkg_proto_matching_engine_proto_depIdxs = []int32{
	0, // 0: tcb.matching_engine.Order.Type:type_name -> tcb.matching_engine.Side
	4, // 1: tcb.matching_engine.BookOutput.Buys:type_name -> tcb.matching_engine.BookArray
	4, // 2: tcb.matching_engine.BookOutput.Sells:type_name -> tcb.matching_engine.BookArray
	1, // 3: tcb.matching_engine.Engine.Process:input_type -> tcb.matching_engine.Order
	1, // 4: tcb.matching_engine.Engine.ProcessMarket:input_type -> tcb.matching_engine.Order
	1, // 5: tcb.matching_engine.Engine.Cancel:input_type -> tcb.matching_engine.Order
	3, // 6: tcb.matching_engine.Engine.FetchBook:input_type -> tcb.matching_engine.BookInput
	2, // 7: tcb.matching_engine.Engine.Process:output_type -> tcb.matching_engine.OutputOrders
	2, // 8: tcb.matching_engine.Engine.ProcessMarket:output_type -> tcb.matching_engine.OutputOrders
	1, // 9: tcb.matching_engine.Engine.Cancel:output_type -> tcb.matching_engine.Order
	5, // 10: tcb.matching_engine.Engine.FetchBook:output_type -> tcb.matching_engine.BookOutput
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_matching_engine_proto_init() }
func file_pkg_proto_matching_engine_proto_init() {
	if File_pkg_proto_matching_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_matching_engine_proto_rawDesc), len(file_pkg_proto_matching_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_matching_engine_proto_goTypes,
		DependencyIndexes: file_pkg_proto_matching_engine_proto_depIdxs,
		EnumInfos:         file_pkg_proto_matching_engine_proto_enumTypes,
		MessageInfos:      file_pkg_proto_matching_engine_proto_msgTypes,
	}.Build()
	File_pkg_proto_matching_engine_proto = out.File
	file_pkg_proto_matching_engine_proto_goTypes = nil
	file_pkg_proto_matching_engine_proto_depIdxs = nil
}
