// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: pkg/proto/matching-engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_buy  Side = 0
	Side_sell Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "buy",
		1: "sell",
	}
	Side_value = map[string]int32{
		"buy":  0,
		"sell": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_matching_engine_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_pkg_proto_matching_engine_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         Side   `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=tcb.matching_engine.Side" json:"Type,omitempty"`
	ID           string `protobuf:"bytes,2,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Amount       string `protobuf:"bytes,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price        string `protobuf:"bytes,4,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	Pair         string `protobuf:"bytes,5,opt,name=Pair,json=pair,proto3" json:"Pair,omitempty"`
	FilledAmount string `protobuf:"bytes,6,opt,name=FilledAmount,json=filled_amount,proto3" json:"FilledAmount,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetType() Side {
	if x != nil {
		return x.Type
	}
	return Side_buy
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Order) GetFilledAmount() string {
	if x != nil {
		return x.FilledAmount
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{1}
}

type OrderUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType      string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp      int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pair           string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	Order          *Order `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	MatchedWith    *Order `protobuf:"bytes,5,opt,name=matched_with,json=matchedWith,proto3" json:"matched_with,omitempty"`
	TradeAmount    string `protobuf:"bytes,6,opt,name=trade_amount,json=tradeAmount,proto3" json:"trade_amount,omitempty"`
	ExecutionPrice string `protobuf:"bytes,7,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"`
}

func (x *OrderUpdateEvent) Reset() {
	*x = OrderUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateEvent) ProtoMessage() {}

func (x *OrderUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateEvent.ProtoReflect.Descriptor instead.
func (*OrderUpdateEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{2}
}

func (x *OrderUpdateEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OrderUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderUpdateEvent) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *OrderUpdateEvent) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderUpdateEvent) GetMatchedWith() *Order {
	if x != nil {
		return x.MatchedWith
	}
	return nil
}

func (x *OrderUpdateEvent) GetTradeAmount() string {
	if x != nil {
		return x.TradeAmount
	}
	return ""
}

func (x *OrderUpdateEvent) GetExecutionPrice() string {
	if x != nil {
		return x.ExecutionPrice
	}
	return ""
}

type OutputOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdersProcessed string `protobuf:"bytes,1,opt,name=OrdersProcessed,json=orders_processed,proto3" json:"OrdersProcessed,omitempty"`
	PartialOrder    string `protobuf:"bytes,2,opt,name=PartialOrder,json=partial_order,proto3" json:"PartialOrder,omitempty"`
}

func (x *OutputOrders) Reset() {
	*x = OutputOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputOrders) ProtoMessage() {}

func (x *OutputOrders) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputOrders.ProtoReflect.Descriptor instead.
func (*OutputOrders) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{3}
}

func (x *OutputOrders) GetOrdersProcessed() string {
	if x != nil {
		return x.OrdersProcessed
	}
	return ""
}

func (x *OutputOrders) GetPartialOrder() string {
	if x != nil {
		return x.PartialOrder
	}
	return ""
}

type BookInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair  string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *BookInput) Reset() {
	*x = BookInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInput) ProtoMessage() {}

func (x *BookInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInput.ProtoReflect.Descriptor instead.
func (*BookInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{4}
}

func (x *BookInput) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *BookInput) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BookArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PriceAmount []string `protobuf:"bytes,1,rep,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
}

func (x *BookArray) Reset() {
	*x = BookArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookArray) ProtoMessage() {}

func (x *BookArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookArray.ProtoReflect.Descriptor instead.
func (*BookArray) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{5}
}

func (x *BookArray) GetPriceAmount() []string {
	if x != nil {
		return x.PriceAmount
	}
	return nil
}

type BookOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buys  []*BookArray `protobuf:"bytes,1,rep,name=Buys,proto3" json:"Buys,omitempty"`
	Sells []*BookArray `protobuf:"bytes,2,rep,name=Sells,proto3" json:"Sells,omitempty"`
}

func (x *BookOutput) Reset() {
	*x = BookOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_matching_engine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookOutput) ProtoMessage() {}

func (x *BookOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_matching_engine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookOutput.ProtoReflect.Descriptor instead.
func (*BookOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_matching_engine_proto_rawDescGZIP(), []int{6}
}

func (x *BookOutput) GetBuys() []*BookArray {
	if x != nil {
		return x.Buys
	}
	return nil
}

func (x *BookOutput) GetSells() []*BookArray {
	if x != nil {
		return x.Sells
	}
	return nil
}

var File_pkg_proto_matching_engine_proto protoreflect.FileDescriptor

var file_pkg_proto_matching_engine_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x2d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69,
	0x72, 0x12, 0x23, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa0, 0x02, 0x0a, 0x10, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72,
	0x12, 0x30, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x77, 0x69,
	0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x57, 0x69, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x5e, 0x0a,
	0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a,
	0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x35, 0x0a,
	0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x2e, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x76, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x42, 0x75, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x52, 0x04, 0x42, 0x75, 0x79, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x65, 0x6c, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x53, 0x65, 0x6c, 0x6c, 0x73, 0x2a, 0x19, 0x0a, 0x04,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x73, 0x65, 0x6c, 0x6c, 0x10, 0x01, 0x32, 0x9d, 0x03, 0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x2e,
	0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x21, 0x2e, 0x74, 0x63, 0x62, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x4e, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e,
	0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x21, 0x2e, 0x74, 0x63, 0x62, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x06,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4c,
	0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1e, 0x2e, 0x74, 0x63,
	0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x63,
	0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x69, 0x0a, 0x17,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x74, 0x63, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_matching_engine_proto_rawDescOnce sync.Once
	file_pkg_proto_matching_engine_proto_rawDescData = file_pkg_proto_matching_engine_proto_rawDesc
)

func file_pkg_proto_matching_engine_proto_rawDescGZIP() []byte {
	file_pkg_proto_matching_engine_proto_rawDescOnce.Do(func() {
		file_pkg_proto_matching_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_matching_engine_proto_rawDescData)
	})
	return file_pkg_proto_matching_engine_proto_rawDescData
}

var file_pkg_proto_matching_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_matching_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_matching_engine_proto_goTypes = []interface{}{
	(Side)(0),                // 0: tcb.matching_engine.Side
	(*Order)(nil),            // 1: tcb.matching_engine.Order
	(*SubscribeRequest)(nil), // 2: tcb.matching_engine.SubscribeRequest
	(*OrderUpdateEvent)(nil), // 3: tcb.matching_engine.OrderUpdateEvent
	(*OutputOrders)(nil),     // 4: tcb.matching_engine.OutputOrders
	(*BookInput)(nil),        // 5: tcb.matching_engine.BookInput
	(*BookArray)(nil),        // 6: tcb.matching_engine.BookArray
	(*BookOutput)(nil),       // 7: tcb.matching_engine.BookOutput
}
var file_pkg_proto_matching_engine_proto_depIdxs = []int32{
	0,  // 0: tcb.matching_engine.Order.Type:type_name -> tcb.matching_engine.Side
	1,  // 1: tcb.matching_engine.OrderUpdateEvent.order:type_name -> tcb.matching_engine.Order
	1,  // 2: tcb.matching_engine.OrderUpdateEvent.matched_with:type_name -> tcb.matching_engine.Order
	6,  // 3: tcb.matching_engine.BookOutput.Buys:type_name -> tcb.matching_engine.BookArray
	6,  // 4: tcb.matching_engine.BookOutput.Sells:type_name -> tcb.matching_engine.BookArray
	1,  // 5: tcb.matching_engine.Engine.Process:input_type -> tcb.matching_engine.Order
	1,  // 6: tcb.matching_engine.Engine.ProcessMarket:input_type -> tcb.matching_engine.Order
	1,  // 7: tcb.matching_engine.Engine.Cancel:input_type -> tcb.matching_engine.Order
	5,  // 8: tcb.matching_engine.Engine.FetchBook:input_type -> tcb.matching_engine.BookInput
	2,  // 9: tcb.matching_engine.Engine.SubscribeToOrderUpdates:input_type -> tcb.matching_engine.SubscribeRequest
	4,  // 10: tcb.matching_engine.Engine.Process:output_type -> tcb.matching_engine.OutputOrders
	4,  // 11: tcb.matching_engine.Engine.ProcessMarket:output_type -> tcb.matching_engine.OutputOrders
	1,  // 12: tcb.matching_engine.Engine.Cancel:output_type -> tcb.matching_engine.Order
	7,  // 13: tcb.matching_engine.Engine.FetchBook:output_type -> tcb.matching_engine.BookOutput
	3,  // 14: tcb.matching_engine.Engine.SubscribeToOrderUpdates:output_type -> tcb.matching_engine.OrderUpdateEvent
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_matching_engine_proto_init() }
func file_pkg_proto_matching_engine_proto_init() {
	if File_pkg_proto_matching_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_matching_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_matching_engine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_matching_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_matching_engine_proto_goTypes,
		DependencyIndexes: file_pkg_proto_matching_engine_proto_depIdxs,
		EnumInfos:         file_pkg_proto_matching_engine_proto_enumTypes,
		MessageInfos:      file_pkg_proto_matching_engine_proto_msgTypes,
	}.Build()
	File_pkg_proto_matching_engine_proto = out.File
	file_pkg_proto_matching_engine_proto_rawDesc = nil
	file_pkg_proto_matching_engine_proto_goTypes = nil
	file_pkg_proto_matching_engine_proto_depIdxs = nil
}
