permissions:
  contents: read
  packages: write

name: Github Container Registry Continue Integration

on:
  push:
    branches:
      - 'master'
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/matching-engine

jobs:
  docker:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Get short SHA"
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA}| cut -c1-8`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/tcb-odds/matching-engine:${{env.SHORT_SHA}}
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy to Ubuntu server (SSH)
        uses: appleboy/ssh-action@v1
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          SHORT_SHA: ${{ env.SHORT_SHA }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd /home/tcb/server
            cp docker-compose.yaml docker-compose.yaml.bak.$(date +%s)

            SERVICE="matching-engine"
            yq eval -i ".services[\"$SERVICE\"].image = \"${{env.IMAGE_NAME}}:${{env.SHORT_SHA}}\"" docker-compose.yaml          

            echo "=== Updated docker‑compose.yaml ==="
            grep -A2 "image:" -n docker-compose.yaml | grep "${SERVICE}" -A1

            docker compose pull ${SERVICE}

            docker compose up -d --no-deps ${SERVICE}